---

- name: Backup Cisco Device
  hosts: Cisco
  gather_facts: false
  connection: network_cli
  
  tasks: 
     - name: show running config
       ios_command:
         commands:
         - show running-config 
       register: config
     - name: Save to local directory 
       copy:
        content: "{{ config.stdout | replace ('\\n', '\n')}}"
        dest: "show-output/{{ inventory_hostname }}.backup" 
